### PR TITLE
deepai api added

### PR DESCRIPTION
**Pull request by ashishsonam**

### CODE REVIEW

**Comment by ashishsonam** [comment]
abeeeee file hi delete kr diya :(

**Comment by hipstermf** [comment]
Abe meko nehi chalate ata hai GitHub

**Comment by ashishsonam** [comment]
wapas daal wo file

**Comment by ashishsonam** [comment]
uske baad jo mera PR hai usko bas merge kr de

**Comment by hipstermf** [comment]
Abe merge kaise karu

**Pull request closed without merging**
